### PR TITLE
Dialyzer Cleanup

### PR DESCRIPTION
**Pull request by beerriot**
Major thanks to @kostis, @cmeiklejohn, and @andrewjstone for sitting with me last week and plowing through Dialyzer's complaints about riak_pipe. This PR fixes the things we found:
- incorrect types - mostly switching from non-exported things to exported things, but also a little refactoring to make code cleaner and not rely on non-exported types
- unmatched returns - often just being explicit about not caring what a return value is, but also many cases where functions should have failed if calls didn't return success (mostly in testing code, but good to have our tests be pickier)
- missing function parameters - just a completely incorrect call that might have been exploding

All eunit tests pass all pipe_\* and mapred_\* riak_test cases pass locally for me, except `mapred_basic_compat`, which is known broken currently.

### CODE REVIEW

**Comment by cmeiklejohn** [comment]
@beerriot Can we add the updated rebar to this repo?  Eunit passes, but I can't run Dialyzer standalone on the repository because the version of rebar included doesn't correctly handle the protobuffs dependency.

```
dialyzer: Could not get abstract code for file: /Users/cmeiklejohn/Repositories/riak_pipe/deps/riak_core/ebin/riak_core_pb.beam 
(please recompile it with +debug_info)
```

**Comment by beerriot** [comment]
@cmeiklejohn That's odd. That's what commit 8b24edb did. That version worked for me with R16B02.

**Comment by cmeiklejohn** [comment]
I hope you don't mind, but I've also added a couple commits to this branch: 

b1248ff465bd4e2030abc207d0fa25dcfec0ffcd, which ensures that the compile target depends on the dependencies target
c1aa0e6d9319c2f07ea1335f36bd3c6fac3ba651, only run Dialyzer on the riak_pipe application

Also, I've rebuild all deps from scratch and was able to run the Dialyzer without issue.  

:+1:

**Comment by beerriot** [comment]
Excellent, thanks @cmeiklejohn!

**Pull request merged**
